packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  better-sqlite3: true
  core-js: false
  esbuild: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.50.6 || 1.51.0'
  - '@posthog/types@1.409.1'
  - posthog-node@5.51.7
  - '@posthog/browser-common@0.8.2'
  - posthog-js@1.428.3
