import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { getThemeBundle } from "@mercatus-liber/theming";
import { MANIFEST_FILENAME, serializeManifest, type AdapterChoice, type StoreManifest } from "./manifest.js";

export interface ScaffoldOptions {
  targetDir: string;
  storeName: string;
  adapter: AdapterChoice;
  theme: string;
  plugins?: string[];
  /** Scaffold into a non-empty directory anyway. Defaults to false -- scaffoldStore never silently clobbers existing content. */
  overwrite?: boolean;
}

export class TargetDirNotEmptyError extends Error {
  constructor(dir: string) {
    super(`Target directory is not empty: ${dir} -- pass overwrite: true to scaffold into it anyway.`);
    this.name = "TargetDirNotEmptyError";
  }
}

export class InvalidThemeError extends Error {
  constructor(theme: string) {
    super(`Unknown theme bundle key: "${theme}"`);
    this.name = "InvalidThemeError";
  }
}

const ADAPTER_PACKAGES: Record<AdapterChoice, string> = {
  sqlite: "@mercatus-liber/adapter-sqlite",
  postgres: "@mercatus-liber/adapter-postgres",
  shopify: "@mercatus-liber/adapter-shopify",
};

const CORE_PACKAGES = ["@mercatus-liber/core", "@mercatus-liber/catalog", "@mercatus-liber/cart", "@mercatus-liber/checkout-orders", "@mercatus-liber/theming"];

/**
 * Matches the version scheme every package in this monorepo currently
 * ships at. Once these packages are actually published to npm (see this
 * epic's docs/deploy-tool-scope.md), this becomes "the latest published
 * version at scaffold time" instead of a fixed constant.
 */
const PACKAGE_VERSION_RANGE = "^0.1.0";

export async function scaffoldStore(options: ScaffoldOptions): Promise<void> {
  const { targetDir, storeName, adapter, theme, plugins = [], overwrite = false } = options;

  if (!getThemeBundle(theme)) throw new InvalidThemeError(theme);

  await mkdir(targetDir, { recursive: true });
  if (!overwrite) {
    const existing = await readdir(targetDir);
    if (existing.length > 0) throw new TargetDirNotEmptyError(targetDir);
  }

  const dependencies: Record<string, string> = { [ADAPTER_PACKAGES[adapter]]: PACKAGE_VERSION_RANGE };
  for (const pkg of CORE_PACKAGES) dependencies[pkg] = PACKAGE_VERSION_RANGE;
  if (adapter === "postgres") dependencies.pg = "^8.13.0";

  const packageJson = {
    name: storeName,
    version: "0.1.0",
    private: true,
    type: "module",
    dependencies,
  };

  await writeFile(path.join(targetDir, "package.json"), `${JSON.stringify(packageJson, null, 2)}\n`, "utf8");
  await writeFile(path.join(targetDir, "services.ts"), generateServicesFile(adapter, theme), "utf8");

  const manifest: StoreManifest = {
    storeName,
    adapter,
    theme,
    plugins,
    packageVersions: dependencies,
    generatedAt: new Date().toISOString(),
  };
  await writeFile(path.join(targetDir, MANIFEST_FILENAME), serializeManifest(manifest), "utf8");
}

function generateServicesFile(adapter: AdapterChoice, theme: string): string {
  const adapterImport = {
    sqlite: `import { createSqliteAdapter } from "@mercatus-liber/adapter-sqlite";`,
    postgres: `import { createPostgresAdapter } from "@mercatus-liber/adapter-postgres";\nimport { Pool } from "pg";`,
    shopify: `import { createShopifyAdapter } from "@mercatus-liber/adapter-shopify";`,
  }[adapter];

  const adapterConstruction = {
    sqlite: `const persistence = createSqliteAdapter(process.env.DATABASE_PATH ?? ":memory:");`,
    postgres: `const pool = new Pool({ connectionString: process.env.DATABASE_URL });\n  const persistence = await createPostgresAdapter(pool);`,
    shopify: `const persistence = createShopifyAdapter({ shop: process.env.SHOPIFY_SHOP!, accessToken: process.env.SHOPIFY_ACCESS_TOKEN! });`,
  }[adapter];

  return `/**
 * Generated by @mercatus-liber/create-store. The ONLY module in this
 * project that should import a concrete adapter -- same single-seam rule
 * apps/reference-storefront/lib/services.ts follows in the main repo.
 * Chosen adapter: ${adapter}. Chosen theme: ${theme}.
 *
 * This is a starting point covering catalog/cart/theming wiring, not a
 * full copy of the reference storefront's composition (checkout/payments/
 * cms/inventory/analytics/ai-interface wiring follow the identical
 * pattern -- see apps/reference-storefront/lib/services.ts in the main
 * repo for the complete reference).
 */
import { createCatalogService } from "@mercatus-liber/catalog";
import { createCartService, createInMemoryCartRepository } from "@mercatus-liber/cart";
import { createInMemoryEventBus } from "@mercatus-liber/core";
import { applyTheme, createThemingService, getThemeBundle } from "@mercatus-liber/theming";
${adapterImport}

export async function buildServices() {
  const events = createInMemoryEventBus();
  ${adapterConstruction}
  const catalog = createCatalogService({ persistence, events });
  const cart = createCartService({ repository: createInMemoryCartRepository(), skus: catalog, events });

  const theming = createThemingService();
  const bundle = getThemeBundle("${theme}");
  if (bundle) applyTheme(theming, bundle);

  return { events, catalog, cart, theming };
}
`;
}
