/**
 * Printify v1 API shapes this adapter actually calls, confirmed 2026-09-09 against
 * Printify's real, current, LIVE public API reference -- NOT the backlog addendum's
 * directional summary, and NOT training-data recall. Confirmed by fetching
 * developers.printify.com's raw HTML directly (its single-page doc is long enough
 * that a summarizing fetch truncates before reaching the Webhooks section, so the
 * page was pulled with `curl` and grepped/quoted verbatim instead -- same "don't
 * trust a lossy render, go to the primary source" discipline that mattered for
 * epic 42's Printful research), cross-referenced against:
 *   - developers.printify.com's own downloadable OpenAPI spec (`openapi.json`,
 *     linked directly from the docs page) for the request/response schema shapes,
 *   - the community Node SDK generated by hand against that same live API
 *     (github.com/spencerlepine/printify-sdk-js, `src/v1/orders/*.ts` and
 *     `src/v1/types.ts`) as a second, independent confirmation of field names.
 *
 * Research finding 1 -- external-id field (design-discussion.md's item (c) /
 * this story's question 1): CONFIRMED. Two distinct, real, documented
 * `external_id` fields, at two different levels, both optional strings:
 *   - ORDER level: `SubmitOrderRequest.external_id` -- "Unique identifier of the
 *     order from the external system" (quoted verbatim from the docs' "Submit an
 *     order" example: `"external_id": "2750e210-39bb-11e9-a503-452618153e4a"`).
 *     This adapter sets it to our own `orderId`.
 *   - LINE ITEM level: each line item's own `external_id` -- documented verbatim
 *     as "Unique identifier of the line item from the external system. Preserved
 *     during replacements and routing." This adapter sets it to our own `skuId`,
 *     the same order-level/item-level split Printful's real v2 API also has (see
 *     adapter-printful's printful-types.ts finding 1) -- not a coincidence, a
 *     genuinely common POD-API pattern.
 *
 * Real, disclosed internal inconsistency in Printify's own docs, worth
 * recording rather than silently picking one and hoping: the docs' own
 * "Order submission properties" table marks order-level `external_id`
 * REQUIRED ("A unique string identifier from the sales channel specifying the
 * order name or id"), while the docs' worked "Submit an order" example
 * section and the downloadable OpenAPI spec's generated request-body type
 * both show it without an explicit required marker. This adapter follows the
 * stricter, REQUIRED reading (the structured property table, not just an
 * example) and always sends it, set to our own `orderId` -- a real string is
 * always available from `SubmitFulfillmentOrderInput`, so this costs nothing
 * either way. Separately, and confirmed by direct inspection of the docs'
 * own illustrated `GET .../orders/{id}.json` response example: it does NOT
 * echo an order-level `external_id` field back at all (only `id`/
 * `app_order_id`), despite `external_id` being required on submission. This
 * is why `getOrderStatus` below needs its own bridge (see index.ts's
 * `resolveExternalOrderId`) rather than reusing Printful's `@external_id`
 * addressing trick, which Printify's docs show no equivalent for.
 *
 * Research finding 2 -- POST /v1/shops/{shop_id}/orders.json request schema
 * (this story's question 3): CONFIRMED, directly from the docs' "Submit an order"
 * section, which documents THREE mutually-exclusive real line-item shapes:
 *   - by existing product: `{ product_id, variant_id, quantity, external_id? }`;
 *   - by blueprint (create-a-product-on-the-fly): `{ print_provider_id,
 *     blueprint_id, variant_id, print_areas, quantity, external_id?,
 *     print_details? }`;
 *   - by SKU: `{ sku, quantity, external_id? }` (documented in the OpenAPI spec's
 *     "Format C" for `submitOrderRequest`, not spelled out in the same worked
 *     example the docs page shows, but a real, distinct schema branch).
 * Top-level body: `{ external_id (REQUIRED, see above), label?, line_items:
 * LineItem[], shipping_method?, is_printify_express?, is_economy_shipping?,
 * send_shipping_notification?, address_to: Address }`. Response is just
 * `{ id: string }` (confirmed verbatim in the docs' "View Response" panel).
 * This adapter uses the by-product shape (`PrintifyProductLineItemInput` below)
 * -- the same "caller already knows which catalog product/variant to order"
 * boundary design-discussion.md §1a draws for provider/product selection being
 * out of this adapter's own scope.
 *
 * Real, confirmed, and NOT to be conflated with Printful's flow: Printify's
 * order lifecycle is genuinely two real API calls, same shape as Printful's
 * draft-then-confirm --
 *   `POST /v1/shops/{shop_id}/orders.json` creates the order (status starts
 *   `pending`/`on-hold`, UNCHARGED -- confirmed in the docs' own order-status
 *   table: "on-hold ... Users can edit orders in this status"), then
 *   `POST /v1/shops/{shop_id}/orders/{order_id}/send_to_production.json`
 *   (confirmed path, from the community SDK's `sendToProduction.ts`, matching
 *   the docs' own event description "order:sent-to-production ... The order was
 *   sent to production") moves it to `sending-to-production`/`in-production` and
 *   is the real point Printify actually charges the merchant's payment method
 *   on file (design-discussion.md's own confirmed "charged only when an order
 *   moves to production" finding). Both calls happen inside this adapter's
 *   single `submitOrder`, mirroring exactly how adapter-printful's `submitOrder`
 *   makes two real calls (create + confirm) for the analogous reason.
 *
 * Real, confirmed order-status enum (11 values, docs' own "Order properties"
 * table, quoted verbatim below) -- richer than `FulfillmentLineStatus`'s 4
 * values, same genuine, disclosed narrowing as Printful's case (see mapping.ts):
 *   `pending`, `on-hold`, `sending-to-production`, `in-production`, `canceled`,
 *   `fulfilled`, `partially-fulfilled`, `payment-not-received`, `has-issues`,
 *   `cost-calculation`, `unfulfillable`.
 *
 * Research finding 3 -- rate limits (this story's question 2, flagged
 * "unconfirmed" by the addendum): CONFIRMED, quoted verbatim from
 * developers.printify.com's own "Rate limits" section:
 *   - Global: "600 requests per minute." Exceeding -> HTTP 429.
 *   - Catalog API endpoints: an ADDITIONAL separate "100 requests per minute per
 *     integration (per account, not per access token)".
 *   - Product-publishing endpoint: "200 requests per 30 minutes" ("product
 *     creation as a result of Order creation is not limited" -- so this
 *     adapter's own order-creation calls are NOT subject to that narrower cap).
 *   - "Requests resulting in an error response may not exceed 5% of your total
 *     requests" (an error-rate ceiling, not just a request-count one).
 * Unlike Printful's 120/min (a single flat number), Printify's is tiered by
 * endpoint category -- this adapter does not implement client-side rate
 * limiting itself (same scope boundary as adapter-printful), but the real
 * numbers are recorded here for whoever wires retry/backoff later.
 *
 * Research finding 4 -- webhook payload/signature format (this story's
 * question 4): CONFIRMED -- genuinely NOT in the same "unconfirmable from
 * public docs" bucket as Printful's v2 webhook signature (see
 * adapter-printful's webhook.ts for that contrast). Printify's docs have a
 * dedicated "Securing your Webhooks" section, quoted verbatim:
 *   - A webhook subscription optionally carries its own `secret` field, set at
 *     creation (`POST /v1/shops/{shop_id}/webhooks.json` body: `{ topic, url,
 *     secret? }` -- confirmed in the docs' "Webhook properties" table and the
 *     community SDK's `NewWebhook` type).
 *   - "When your secret token is set, Printify will use it to create a hash
 *     signature with each payload body. Printify uses an HMAC hexdigest to
 *     compute the hash sha256 signature with your provided secret."
 *   - "This payload body signature is passed along with each request in the
 *     headers as `X-Pfy-Signature`. The signature format is: `sha256={digest}`."
 *     (confirmed example header: `x-pfy-signature:
 *     sha256=4260d30ec4ee2a17181ae5072c846d8dfcb5ceb195e24de055fd9a21d8c6648f`).
 *   - The docs' own validation guidance: compute an HMAC-SHA256 hex digest of
 *     the raw request body with the shared secret, compare against the header
 *     using a constant-time comparison.
 * Because this is genuinely confirmed (not guessed), webhook.ts implements this
 * scheme directly as the DEFAULT verifier (unlike adapter-printful's
 * fail-closed-with-no-default posture, which was the right call there only
 * because the format was genuinely unconfirmable) -- a caller can still
 * override it via `verifyWebhookSignature` for e.g. a rotated/multi-secret
 * setup, but does not have to supply one just to get a working adapter.
 *
 * Real, confirmed webhook envelope shape (docs' own "Event properties" +
 * "Payload examples" sections, quoted verbatim):
 *   `{ id: string, type: string, created_at: string, resource: { id: string,
 *   type: "shop" | "product" | "order" | "personalization-preview-task",
 *   data: unknown } }`
 * -- notably NOT the `{ type, data }` shape adapter-printful's Printful research
 * confirmed; a real, disclosed difference between the two providers' webhook
 * envelopes, not an inconsistency in this adapter's own code.
 *
 * Real, confirmed order-event topic strings (docs' own "Order events" table):
 * `order:created`, `order:updated`, `order:sent-to-production`,
 * `order:shipment:created`, `order:shipment:delivered` -- the five this
 * adapter's `handleWebhookEvent` recognizes by name. Real topics beyond these
 * (`shop:disconnected`, `product:*`, `personalization-preview-task:processed`)
 * exist and are intentionally passed through as `"other"` rather than rejected,
 * same discipline as adapter-printful's `parsePrintfulWebhookPayload`.
 *
 * The real, confirmed `order:shipment:created`/`order:shipment:delivered`
 * webhook payload's `resource.data` shape (quoted verbatim from the docs'
 * "Payload examples"): `{ shop_id, shipped_at | delivered_at, carrier: { code,
 * tracking_number, tracking_url }, skus: string[] }` -- note this is a
 * genuinely DIFFERENT shape than the `Order.shipments[]` array's own fields
 * (`carrier`/`number`/`url`/`delivered_at`, confirmed in the docs' "Order
 * properties" table and mirrored in the community SDK's `OrderShipment` type)
 * -- the webhook's nested `carrier.tracking_number`/`carrier.tracking_url`
 * versus the polled order's flat `number`/`url`. A real, disclosed shape
 * mismatch between Printify's push (webhook) and pull (GET order) surfaces for
 * the same underlying fact, not an implementation error in mapping.ts.
 */

/**
 * Printify v1 `Address` (`address_to`) -- confirmed field names (docs' "Order
 * properties" + "Submit an order" example). The docs mark `first_name`/
 * `last_name`/`address1`/`city`/`zip`/`email`/`phone`/`country` REQUIRED for a
 * real order to actually be accepted -- modeled here as all-optional anyway
 * (same posture as adapter-printful's `PrintfulAddress`: "Printful itself
 * rejects a request with too little address data, this adapter does not
 * re-validate") so this type can be shared directly with `PrintifyRecipientAddress`
 * (mapping.ts) without a lossy bridge conversion.
 */
export interface PrintifyAddress {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  country?: string;
  region?: string;
  address1?: string;
  address2?: string;
  city?: string;
  zip?: string;
  company?: string;
}

/** A line item ordering an existing catalog product -- the shape this adapter uses (confirmed in the docs' "Submit an order" -> "Order an existing product" example). */
export interface PrintifyProductLineItemInput {
  product_id: string;
  variant_id: number;
  quantity: number;
  external_id?: string;
}

/** `POST /v1/shops/{shop_id}/orders.json` request body -- confirmed shape (docs' "Submit an order" section). `external_id` is REQUIRED per the docs' own "Order submission properties" table -- see this file's top comment for the disclosed inconsistency with the worked example/OpenAPI type, which don't mark it required. */
export interface PrintifySubmitOrderRequest {
  external_id: string;
  label?: string;
  line_items: PrintifyProductLineItemInput[];
  shipping_method?: number;
  is_printify_express?: boolean;
  is_economy_shipping?: boolean;
  send_shipping_notification?: boolean;
  address_to: PrintifyAddress;
}

/** `POST /v1/shops/{shop_id}/orders.json` response body -- confirmed shape (docs' "View Response" panel: just `{ id }`). */
export interface PrintifySubmitOrderResponse {
  id: string;
}

/**
 * The real, documented, 11-value order-status enum (docs' own "Order
 * properties" table, quoted verbatim in this file's top comment). Richer than
 * `FulfillmentLineStatus`'s 4 values -- see mapping.ts for the disclosed
 * narrowing.
 */
export type PrintifyOrderStatus =
  | "pending"
  | "on-hold"
  | "sending-to-production"
  | "in-production"
  | "canceled"
  | "fulfilled"
  | "partially-fulfilled"
  | "payment-not-received"
  | "has-issues"
  | "cost-calculation"
  | "unfulfillable";

/**
 * One line item as Printify echoes it back on
 * `GET /v1/shops/{shop_id}/orders/{order_id}.json` -- confirmed fields (docs'
 * "Line item properties" table). Real, disclosed inconsistency confirmed by
 * direct inspection of the docs' own illustrated response example (the "Get
 * order details by ID" section): the "Line item properties" table lists
 * `external_id` as a top-level sibling of `product_id`/`variant_id`, but the
 * actual worked JSON example nests it inside `metadata.external_id` instead
 * (`"metadata": { "title": ..., "sku": ..., "external_id": "line-item-abc-001"
 * }`) -- both are modeled here so `resolveSkuId` (mapping.ts) can read
 * whichever one a real API response actually populates rather than betting on
 * a single interpretation of Printify's own inconsistent docs.
 */
export interface PrintifyOrderLineItemResponse {
  product_id?: string;
  variant_id: number;
  quantity: number;
  print_provider_id?: number;
  cost?: number;
  shipping_cost?: number;
  status?: string;
  external_id?: string | null;
  metadata?: { external_id?: string | null; sku?: string; title?: string };
  sent_to_production_at?: string;
  fulfilled_at?: string;
}

/**
 * `Order.shipments[]` -- confirmed real fields (docs' "Order properties" table
 * and the community SDK's `OrderShipment` type): `carrier`/`number`/`url`/
 * `delivered_at`. NOTE this is a different shape than the webhook's own
 * `resource.data.carrier` object (see this file's top comment) -- both are
 * real, from the same provider, for the same underlying fact.
 */
export interface PrintifyOrderShipment {
  carrier: string;
  number: string;
  url: string;
  delivered_at: string;
}

/** `GET /v1/shops/{shop_id}/orders/{order_id}.json` response -- only the fields this adapter reads (docs' "Order properties" table). */
export interface PrintifyOrderResponse {
  id: string;
  external_id?: string | null;
  line_items: PrintifyOrderLineItemResponse[];
  status: PrintifyOrderStatus;
  shipments?: PrintifyOrderShipment[];
  created_at?: string;
  sent_to_production_at?: string;
  fulfilled_at?: string;
}

/** `POST /v1/shops/{shop_id}/orders/{order_id}/send_to_production.json` response -- confirmed to echo the order back (community SDK's `sendToProduction.ts`); this adapter only reads the fields `PrintifyOrderResponse` already declares. */
export type PrintifySendToProductionResponse = PrintifyOrderResponse;

/** `POST /v1/shops/{shop_id}/webhooks.json` request body -- confirmed shape (docs' "Webhook properties" table: `secret` is real and OPTIONAL, "Secret that will be used to sign requests for webhook"). */
export interface PrintifyCreateWebhookRequest {
  topic: PrintifyWebhookEventType;
  url: string;
  secret?: string;
}

/** The real, documented order-event topic strings (docs' "Order events" table) this adapter's `handleWebhookEvent` recognizes by name. */
export type PrintifyWebhookEventType = "order:created" | "order:updated" | "order:sent-to-production" | "order:shipment:created" | "order:shipment:delivered";

export const PRINTIFY_WEBHOOK_EVENT_TYPES: readonly PrintifyWebhookEventType[] = [
  "order:created",
  "order:updated",
  "order:sent-to-production",
  "order:shipment:created",
  "order:shipment:delivered",
];

/**
 * The real, confirmed webhook delivery envelope (docs' "Event properties" +
 * "Payload examples" sections) -- `{ id, type, created_at, resource: { id,
 * type, data } }`, genuinely different from Printful's `{ type, data }` shape
 * (see this file's top comment).
 */
export interface PrintifyWebhookPayload {
  id: string;
  type: string;
  created_at: string;
  resource: {
    id: string;
    type: string;
    data: unknown;
  };
}
